### ISSUE TITLE
Convert Id type fields to string before assigning to CustomMetadataValue

### ISSUE THREAD

**Issue by kacrouse** [afawcett/custommetadataapi#1]
`CustomMetadataValue` [only handles primitives](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_Metadata_CustomMetadataValue.htm#apex_class_Metadata_CustomMetadataValue), so it fails on relationship fields. The value just needs to be converted to a string before being assigned. 

I've gotten it to work by changing [line 140](https://github.com/afawcett/custommetadataapi/blob/master/src/classes/CustomMetadata.cls#L139) to this: `cmv.value = dsr.soapType == Schema.SoapType.ID ? String.valueOf(fieldValue) : fieldValue;`

As far as I can tell this is the only type that needs special handling.

**Comment by afawcett** [comment]
Thanks @kacrouse for this fix, i have applied it. 👍
