### ISSUE TITLE
Inner class CustomMetadataTest.MockPlatform is not visible for reuse

### ISSUE THREAD

**Issue by cropredyHelix** [afawcett/custommetadataapi#2]
**Given** 
- one is using the CustomMetadata Service
- one has testmethods that execute code  that deploys Custom Metadata 

**When**
- executing the testmethod

**Then**
- the testmethod fails because  with AsyncException `System.AsyncException: Metadata cannot be deployed from within a test`

Class `CustomMetadataTest` conveniently includes public inner class `MockPlatform` that does useful stuff. However, if you code in your testmethod

    CustomMetadataTest.MockPlatform mockPlatform = new CustomMetadataTest.MockPlatform();
    mockPlatform.xxx = ... // cloning examples from CustomMetadataTest.whenUpsertingByFieldMapSendsEvent
    ....

you get compiler exception that CustomMetadataTest Type is not visible. 

There are some workarounds:
- Reimplement `CustomMetadataTest.MockPlatform` in your own namespace/org (meh)
- Use `!Test.isRunningTest()` to decide whether to execute `String deployId = CustomMetadata.Operations...` (ugh)

Or, the GitHub lib can move class `MockPlatform` to a outer public class
Or, the GitHub lib could make `CustomMetadata` public instead of private
Or ... ?

Since you made `CustomMetadataTest.MockPlatform` public, you must have intended it to be reused in other classes.

Happy to do a PR once I understand your intent.

**Comment by afawcett** [comment]
@cropredyHelix good point! Please make a PR to make it public, that seems like the best option. :+1:

**Comment by afawcett** [comment]
Fixed, thanks @cropredyHelix  👍
