### ISSUE TITLE
Unable to Deploy to Org

### ISSUE THREAD

**Issue by rsoesemann** [afawcett/custommetadataapi#5]
When I try to deploy via button to my dev org it fails with the below error

<img width="1201" alt="github_salesforce_deploy_tool" src="https://user-images.githubusercontent.com/8180281/36025463-72d062c0-0d93-11e8-975c-5c543353cdaa.png">

**Comment by afawcett** [comment]
Yeah i messed up adding the VF demo controller and page, apologies. If you download the code and remove the demo controller class and page you should be good in the meantime.

**Comment by rsoesemann** [comment]
I'll wait for your fix.

**Comment by afawcett** [comment]
Fixed
